-- =============================================================================
-- 열 사전 미등재 11표 보충 (작성 2026-09-19)
--
-- 배경: schema-dict-checker 신설 시 db/schema.sql CREATE TABLE 48개 중 11개가 db/column_dict.csv 에 전혀 등재돼 있지 않았다
--       (clean_dapa_localized_item 15, clean_dapa_overseas_plan 17, clean_krit_task 16, dim_hs10 3, fact_customs_monthly 13, meta_column_dict 6, meta_dataset 23, meta_load_log 10, ref_category_map 10, ref_fsc 6, ref_hs_indicator 16 = 135행).
--       DDL 열 순서·타입·COMMENT 를 기준으로 등재하고, COMMENT 가 없는 열은 docs/db/schema-design.md §2·§3, docs/reference/data-cleaning-rules.md §2 설명으로 채웠다.
--       raw 원본이 없는 표(ref_·meta_·dim_·fact_)의 original_name 은 출처 CSV 열명 또는 '(파생)'.
-- 대상: meta_column_dict. 구조 변경 1건 — dtype VARCHAR(50) → VARCHAR(100)(meta_load_log.stage ENUM 표기 55자가 1차 실행에서 잘림 1265. schema.sql 동일 반영).
-- 실행: RDS admin, scripts/apply_alter.py --twice. 재실행 가능(ON DUPLICATE KEY UPDATE).
-- 기대: meta_column_dict 546 → 681 (= db/column_dict.csv 데이터 행 수). 열 사전 ↔ information_schema.COLUMNS 표 단위 누락 0.
-- =============================================================================

USE defense_dashboard;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE meta_column_dict MODIFY dtype VARCHAR(100) NOT NULL COMMENT '설계 타입(raw는 문자열). ENUM 전체 표기를 위해 2026-09-19 50→100';

INSERT INTO meta_column_dict (table_name, ordinal, column_name, original_name, dtype, description) VALUES
('clean_dapa_localized_item', 1, 'project_name', '사업명', 'VARCHAR(100)', '무기체계 사업명(raw 그대로)'),
('clean_dapa_localized_item', 2, 'part_mgmt_no', '부품관리번호', 'VARCHAR(20)', 'PK. 부품 식별자(완전 중복 8,940행 축약 후 1행)'),
('clean_dapa_localized_item', 3, 'nsn', '재고번호', 'VARCHAR(20)', 'NSN 13자리(공란은 NULL). KDSIS 연결 키'),
('clean_dapa_localized_item', 4, 'fsc4', '군급분류', 'CHAR(4)', 'FSC 4자리 — ref_fsc·국외 API LEFT(invntryNo,4) 조인 키'),
('clean_dapa_localized_item', 5, 'fsc2', '(파생)', 'CHAR(2)', 'LEFT(fsc4,2) — 58·59가 전자 계열'),
('clean_dapa_localized_item', 6, 'item_name', '품명', 'VARCHAR(200)', '품명(raw 그대로. 부품명이며 HS 매핑에 쓰지 않음)'),
('clean_dapa_localized_item', 7, 'contractor_name', '계약업체', 'VARCHAR(200)', '계약 상대(개발 주체 아님). 국산 제조의 증거로 쓰지 않음'),
('clean_dapa_localized_item', 8, 'contractor_name_norm', '(파생)', 'VARCHAR(200)', '업체명 정규화(법인 표기 제거·공백 제거). clean_company_name_link 연결률 보고용'),
('clean_dapa_localized_item', 9, 'last_modified_date', '최종수정일', 'DATE', '포털 스냅샷 수정일. 연도 축으로 쓰지 않음'),
('clean_dapa_localized_item', 10, 'dup_count', '(파생)', 'SMALLINT', '원본 완전 중복 행 수(원본 규모 재현용)'),
('clean_dapa_localized_item', 11, 'is_electronic_group', '(파생)', 'TINYINT(1)', 'fsc2 IN (58,59) = 1. 전자 여부 속성(기본 필터)'),
('clean_dapa_localized_item', 12, 'category', '(파생)', 'VARCHAR(20)', 'ref_category_map(map_type=fsc4) 결과. 미확정이면 NULL'),
('clean_dapa_localized_item', 13, 'category_link_status', '(파생)', 'ENUM(''확정'',''후보'',''대응불가'',''조회표 전용'')', '품목군 연결 상태. 집계 뷰는 확정만 센다(HS6↔FSC4 대응표 미확정이라 현재 전부 미확정)'),
('clean_dapa_localized_item', 14, 'first_raw_row_id', '(파생)', 'BIGINT UNSIGNED', '대표 원본 행 → raw_dapa_localized_item.row_id'),
('clean_dapa_localized_item', 15, 'cleaned_at', '(파생)', 'DATETIME', '정제 시각'),
('clean_dapa_overseas_plan', 1, 'decision_no', '판단번호', 'VARCHAR(20)', 'PK. 국외 조달계획 사업 단위 키(API판 판단번호와 체계 다름 — 조인 금지)'),
('clean_dapa_overseas_plan', 2, 'plan_year', '집행예정월', 'CHAR(4)', '집행예정월 앞 4자리(사건 연도 축)'),
('clean_dapa_overseas_plan', 3, 'plan_month', '집행예정월', 'CHAR(7)', 'YYYY-MM'),
('clean_dapa_overseas_plan', 4, 'rep_item_name', '대표품명', 'VARCHAR(500)', '전자 관련 후보 키워드 분류 대상'),
('clean_dapa_overseas_plan', 5, 'exec_type', '집행유형', 'VARCHAR(30)', '집행유형(TRIM 후)'),
('clean_dapa_overseas_plan', 6, 'contract_method', '계약방법', 'VARCHAR(30)', '계약방법'),
('clean_dapa_overseas_plan', 7, 'exec_agency', '집행기관', 'VARCHAR(100)', '집행기관'),
('clean_dapa_overseas_plan', 8, 'budget_krw', '예산금액', 'BIGINT', '예산금액(원, 집행 예정액 — 실적 아님). 관세청 수입액과 합산·직접 비교 금지'),
('clean_dapa_overseas_plan', 9, 'progress_status', '진행상태', 'VARCHAR(30)', '진행상태(is_contracted 파생 원천)'),
('clean_dapa_overseas_plan', 10, 'is_contracted', '(파생)', 'TINYINT(1)', 'progress_status IN (계약, 부분계약) = 1'),
('clean_dapa_overseas_plan', 11, 'is_electronics_candidate', '(파생)', 'TINYINT(1)', '대표품명 키워드 후보(검수 전) = 1. 후보일 뿐 전자부품 확정 아님'),
('clean_dapa_overseas_plan', 12, 'electronics_review_status', '(파생)', 'ENUM(''미검수'',''확정'',''오탐'',''판단 보류'')', '키워드 후보 검수 상태. 기본 미검수'),
('clean_dapa_overseas_plan', 13, 'system_family_hint', '(파생)', 'VARCHAR(30)', '레이더/통신/항법/전자광학/음탐 등 키워드 계열 라벨(품목군 대응 아님, 집계 축 아님)'),
('clean_dapa_overseas_plan', 14, 'dup_count', '(파생)', 'SMALLINT', '같은 판단번호 원본 행 수'),
('clean_dapa_overseas_plan', 15, 'has_conflict', '(파생)', 'TINYINT(1)', '같은 판단번호에 다른 내용 = 1(기록만, 삭제하지 않음)'),
('clean_dapa_overseas_plan', 16, 'first_raw_row_id', '(파생)', 'BIGINT UNSIGNED', '대표 원본 행 → raw_dapa_overseas_plan.row_id'),
('clean_dapa_overseas_plan', 17, 'cleaned_at', '(파생)', 'DATETIME', '정제 시각'),
('clean_krit_task', 1, 'round_id', '차수(파일명)', 'VARCHAR(10)', 'PK 1. 공고 차수 예 26-1(raw round_label에서 차 제거)'),
('clean_krit_task', 2, 'notice_type', '공고 구분(파일명·본문)', 'ENUM(''예비'',''본공고'',''재공고'',''수정'',''미확인'')', 'PK 2. 예비 / 본공고 / 재공고 / 수정 / 미확인'),
('clean_krit_task', 3, 'task_no', '순', 'SMALLINT', 'PK 3. 표 내 과제 순번'),
('clean_krit_task', 4, 'round_year', '(파생)', 'SMALLINT', 'round_id 앞 2자리 → 20YY(공고 연도 축)'),
('clean_krit_task', 5, 'round_seq', '(파생)', 'TINYINT', 'round_id 뒤 자리(차수 내 회차)'),
('clean_krit_task', 6, 'program_type', '(본문 절 제목)', 'VARCHAR(30)', '핵심부품 / 수출연계 E/L / 전략부품 / 상생협력'),
('clean_krit_task', 7, 'task_name', '국산화 개발대상 과제명', 'VARCHAR(300)', '과제명(품목군 대응 후보 텍스트. HS6 직접 매핑 금지)'),
('clean_krit_task', 8, 'gov_fund_100m_krw', '정부지원\\n연구개발비', 'DECIMAL(10,2)', '정부지원 연구개발비(억원). 원문 23.67억 → 숫자 변환'),
('clean_krit_task', 9, 'dev_period_months', '개발\\n기간', 'SMALLINT', '개발 기간(개월). 원문 30개월 → 숫자 변환'),
('clean_krit_task', 10, 'category', '(파생)', 'VARCHAR(20)', 'ref_category_map(map_type=krit_task) 결과. 미확정이면 NULL'),
('clean_krit_task', 11, 'hs6', '(파생)', 'CHAR(6)', '품목군 대응 HS6(근거 있을 때만). 텍스트 매칭으로 채우지 않음'),
('clean_krit_task', 12, 'category_link_status', '(파생)', 'ENUM(''확정'',''후보'',''대응불가'',''미연결'')', '품목군 연결 상태. 집계 뷰는 확정만 센다'),
('clean_krit_task', 13, 'is_counted', '(파생)', 'TINYINT(1)', '같은 차수 중복 공고(예비→본공고) 중 집계에 쓰는 1건 = 1. 공고 수와 과제 수 구분용'),
('clean_krit_task', 14, 'raw_row_id', '(파생)', 'BIGINT UNSIGNED', '→ raw_krit_task.row_id'),
('clean_krit_task', 15, 'source_file', '(파생)', 'VARCHAR(200)', '추출 CSV 파일명(raw 그대로)'),
('clean_krit_task', 16, 'cleaned_at', '(파생)', 'DATETIME', '정제 시각'),
('dim_hs10', 1, 'hs10', 'hsCd', 'CHAR(10)', 'PK. 관세청 HS10 세부코드(raw_customs_trade 고유값)'),
('dim_hs10', 2, 'hs6', '(파생)', 'CHAR(6)', 'LEFT(hs10,6) → ref_hs_whitelist.hs6'),
('dim_hs10', 3, 'name_ko', 'statKor', 'VARCHAR(300)', 'HS10 품명(코드당 최근 값)'),
('fact_customs_monthly', 1, 'hs10', 'hsCd', 'CHAR(10)', 'PK 1. HS10 → dim_hs10'),
('fact_customs_monthly', 2, 'stat_cd', 'statCd', 'CHAR(2)', 'PK 2. 국가코드 ISO2 → ref_country. NA는 나미비아(결측 아님)'),
('fact_customs_monthly', 3, 'yyyymm', 'year', 'CHAR(6)', 'PK 3. 연월 6자리(raw stat_ym YYYY.MM에서 점 제거). 총계행(is_total=1) 제외'),
('fact_customs_monthly', 4, 'hs6', '(파생)', 'CHAR(6)', 'LEFT(hs10,6) 화이트리스트 키'),
('fact_customs_monthly', 5, 'year', '(파생)', 'SMALLINT', 'yyyymm 앞 4자리'),
('fact_customs_monthly', 6, 'month', '(파생)', 'TINYINT', 'yyyymm 뒤 2자리'),
('fact_customs_monthly', 7, 'imp_dlr', 'impDlr', 'BIGINT', '수입금액(USD, CIF). 국가 전체 수입(민수 포함)'),
('fact_customs_monthly', 8, 'exp_dlr', 'expDlr', 'BIGINT', '수출금액(USD, FOB). 국가 전체 수출(민수 포함)'),
('fact_customs_monthly', 9, 'imp_wgt', 'impWgt', 'BIGINT', '수입중량 kg(참고값, 반올림 오차)'),
('fact_customs_monthly', 10, 'exp_wgt', 'expWgt', 'BIGINT', '수출중량 kg(참고값)'),
('fact_customs_monthly', 11, 'bal_payments', 'balPayments', 'BIGINT', '무역수지(USD) = exp_dlr − imp_dlr'),
('fact_customs_monthly', 12, 'is_partial_year', '(파생)', 'TINYINT(1)', '2026(1~8월) = 1. 연간 실적처럼 쓰지 않음(부분연도 판정의 유일 기준)'),
('fact_customs_monthly', 13, 'raw_row_id', '(파생)', 'BIGINT UNSIGNED', '→ raw_customs_trade.row_id (1:1). 294,420 → 294,174(총계행 246 제외)'),
('meta_column_dict', 1, 'table_name', 'table_name', 'VARCHAR(64)', 'PK 1. db/column_dict.csv 적재본'),
('meta_column_dict', 2, 'ordinal', 'ordinal', 'SMALLINT', 'PK 2. 원본 열 순서(raw_) 또는 DDL 열 순서'),
('meta_column_dict', 3, 'column_name', 'column_name', 'VARCHAR(64)', 'DB 열명(영문 snake_case)'),
('meta_column_dict', 4, 'original_name', 'original_name', 'VARCHAR(100)', '원본 CSV 헤더(줄바꿈은 \\n). 파생 열은 (파생)'),
('meta_column_dict', 5, 'dtype', 'dtype', 'VARCHAR(50)', '설계 타입(raw는 문자열)'),
('meta_column_dict', 6, 'description', 'description', 'VARCHAR(300)', '한글 설명'),
('meta_dataset', 1, 'dataset_key', 'dataset_key', 'VARCHAR(40)', 'PK. 데이터셋 키(db/meta_dataset.csv 적재본). 예 customs_all, dapa_contract'),
('meta_dataset', 2, 'tier', 'tier', 'ENUM(''핵심'',''보조'',''참조'',''메타'')', '핵심 / 보조 / 참조 / 메타'),
('meta_dataset', 3, 'provider', 'provider', 'VARCHAR(100)', '제공기관'),
('meta_dataset', 4, 'dataset_id', 'dataset_id', 'VARCHAR(40)', '공공데이터포털 ID(15050920 등) / KOSIS tblId'),
('meta_dataset', 5, 'title', 'title', 'VARCHAR(200)', '데이터셋 제목'),
('meta_dataset', 6, 'url', 'url', 'VARCHAR(300)', '출처 URL'),
('meta_dataset', 7, 'access_method', 'access_method', 'VARCHAR(50)', 'OpenAPI / 파일 다운로드 / 웹 다운로드 / 수작업'),
('meta_dataset', 8, 'acquired_on', 'acquired_on', 'DATE', '확보일'),
('meta_dataset', 9, 'period_start', 'period_start', 'DATE', '실제 대상 기간 시작(사건 날짜 기준)'),
('meta_dataset', 10, 'period_end', 'period_end', 'DATE', '실제 대상 기간 끝'),
('meta_dataset', 11, 'is_partial_period', 'is_partial_period', 'TINYINT(1)', '부분연도·부분기간 = 1'),
('meta_dataset', 12, 'published_on', 'published_on', 'DATE', '포털 게시일(연도 축으로 쓰지 않음)'),
('meta_dataset', 13, 'updated_on', 'updated_on', 'DATE', '포털 수정일'),
('meta_dataset', 14, 'query_condition', 'query_condition', 'TEXT', '조회 조건·API 호출 파라미터'),
('meta_dataset', 15, 'raw_path', 'raw_path', 'VARCHAR(300)', 'data/raw/... 상대 경로(패턴 허용)'),
('meta_dataset', 16, 'file_bytes', 'file_bytes', 'BIGINT', '파일 크기'),
('meta_dataset', 17, 'sha256', 'sha256', 'CHAR(64)', '단일 파일 해시. 다중 파일은 note에'),
('meta_dataset', 18, 'encoding', 'encoding', 'VARCHAR(20)', 'cp949 / utf-8 / utf-8-sig'),
('meta_dataset', 19, 'parser', 'parser', 'VARCHAR(100)', '건수 집계 파서(pandas read_csv dtype=str 등)'),
('meta_dataset', 20, 'raw_row_count', 'raw_row_count', 'INT', '파서 기준 레코드 수(헤더 제외) — 확보 건수의 기준'),
('meta_dataset', 21, 'portal_row_count', 'portal_row_count', 'INT', '포털 표시 건수(확보 건수가 아님, 다르면 둘 다 기록)'),
('meta_dataset', 22, 'target_table', 'target_table', 'VARCHAR(64)', '적재 대상 raw_ 테이블'),
('meta_dataset', 23, 'note', 'note', 'TEXT', '비고'),
('meta_load_log', 1, 'log_id', '(파생)', 'INT UNSIGNED', 'PK AUTO_INCREMENT'),
('meta_load_log', 2, 'dataset_key', '(파생)', 'VARCHAR(40)', '→ meta_dataset.dataset_key'),
('meta_load_log', 3, 'table_name', '(파생)', 'VARCHAR(64)', '건수를 잰 테이블'),
('meta_load_log', 4, 'stage', '(파생)', 'ENUM(''원본 전체'',''선택 연도 원본'',''중복 처리 후'',''관련 후보'',''검증된 분석 대상'')', '건수 5단계: 원본 전체 → 선택 연도 원본 → 중복 처리 후 → 관련 후보 → 검증된 분석 대상'),
('meta_load_log', 5, 'stage_detail', '(파생)', 'VARCHAR(100)', '예 2025 / HS10 / HS6 집계 / 5분류=방산 장비·부품 후보'),
('meta_load_log', 6, 'row_count', '(파생)', 'INT', '해당 단계 건수'),
('meta_load_log', 7, 'exclusion_reason', '(파생)', 'TEXT', '이전 단계 대비 제외 사유'),
('meta_load_log', 8, 'method', '(파생)', 'TEXT', '집계 SQL 또는 노트북 셀 참조(재현용)'),
('meta_load_log', 9, 'measured_at', '(파생)', 'DATETIME', '측정 시각'),
('meta_load_log', 10, 'measured_by', '(파생)', 'VARCHAR(50)', '측정자(계정·노트북)'),
('ref_category_map', 1, 'map_id', '(파생)', 'INT UNSIGNED', 'PK AUTO_INCREMENT'),
('ref_category_map', 2, 'map_type', '(파생)', 'ENUM(''fsc4'',''contract_group'',''krit_task'')', 'fsc4 / contract_group / krit_task — 품목군 대응 축'),
('ref_category_map', 3, 'source_key', '(파생)', 'VARCHAR(50)', 'FSC4 / 품목군명 / round_id:task_no'),
('ref_category_map', 4, 'category', '(파생)', 'VARCHAR(20)', '반도체 / 전자부품 / 소재장비(화이트리스트 category)'),
('ref_category_map', 5, 'hs6', '(파생)', 'VARCHAR(6)', '대응 HS6. 품목군까지만 연결되면 NULL. 2026-09-17 결정으로 대응표 미확정(공식 연계표 없음) — 현재 행 0'),
('ref_category_map', 6, 'hs6_key', '(파생)', 'VARCHAR(6)', '생성열 COALESCE(hs6,'''') — UNIQUE(map_type, source_key, hs6_key)용'),
('ref_category_map', 7, 'link_status', '(파생)', 'ENUM(''확정'',''후보'',''대응불가'')', '확정 / 후보 / 대응불가. 집계 뷰는 확정만'),
('ref_category_map', 8, 'link_basis', '(파생)', 'TEXT', '연결 근거(문서·표본 검수 결과). 텍스트 매칭은 근거로 인정하지 않음'),
('ref_category_map', 9, 'decided_by', '(파생)', 'VARCHAR(50)', '결정자'),
('ref_category_map', 10, 'decided_at', '(파생)', 'DATE', '결정일'),
('ref_fsc', 1, 'fsc4', '군급', 'CHAR(4)', 'PK. FSC 4자리(군급분류집 756행 중 FSG 그룹행 제외)'),
('ref_fsc', 2, 'fsc2', '(파생)', 'CHAR(2)', 'LEFT(fsc4,2) = FSG'),
('ref_fsc', 3, 'name_ko', '명칭(한글)', 'VARCHAR(200)', '명칭(한글), 최대 104자'),
('ref_fsc', 4, 'name_en', '명칭(영문)', 'VARCHAR(200)', '명칭(영문)'),
('ref_fsc', 5, 'status', '군급상태', 'CHAR(1)', 'A 유효 / C 폐지'),
('ref_fsc', 6, 'is_electronic_group', '(파생)', 'TINYINT(1)', '58xx·59xx = 1 (전자 계열 기본 필터)'),
('ref_hs_indicator', 1, 'indicator_id', '(파생)', 'INT UNSIGNED', 'PK AUTO_INCREMENT'),
('ref_hs_indicator', 2, 'hs6', '(파생)', 'CHAR(6)', '→ ref_hs_whitelist.hs6'),
('ref_hs_indicator', 3, 'axis', '(파생)', 'ENUM(''civil_mix'',''defense_relevance'')', 'civil_mix(민수 혼합) / defense_relevance(방산 관련성) — 화이트리스트 라벨의 정량 근거 축'),
('ref_hs_indicator', 4, 'indicator', '(파생)', 'VARCHAR(30)', '지표명: mil_hs10_share / aero_hs10_share / auto_hs10_share / hsk_control_hs10_ratio / hsk_control_imp_share / b2_part_count / b2_row_count / a7_plan_count / a7_plan_budget / krit_task_count'),
('ref_hs_indicator', 5, 'value_num', '(파생)', 'DECIMAL(18,4)', '비율(%)이면 0~100, 건수·금액이면 그 값'),
('ref_hs_indicator', 6, 'numerator', '(파생)', 'BIGINT', '분자(재현용)'),
('ref_hs_indicator', 7, 'denominator', '(파생)', 'BIGINT', '분모(재현용). 건수 지표는 NULL'),
('ref_hs_indicator', 8, 'unit', '(파생)', 'VARCHAR(10)', '% / 건 / USD / KRW'),
('ref_hs_indicator', 9, 'period_start', '(파생)', 'SMALLINT', '연도. 시점 미상(B2)은 NULL'),
('ref_hs_indicator', 10, 'period_end', '(파생)', 'SMALLINT', '연도'),
('ref_hs_indicator', 11, 'period_key', '(파생)', 'SMALLINT', '생성열 COALESCE(period_start,0) — UNIQUE(hs6, indicator, period_key)용'),
('ref_hs_indicator', 12, 'link_status', '(파생)', 'ENUM(''확정'',''후보'',''해당없음'')', '확정 / 후보 / 해당없음. 대응표 경유 지표만 확정·후보, 관세청 HS10 지표는 해당없음'),
('ref_hs_indicator', 13, 'source', '(파생)', 'VARCHAR(50)', '→ meta_dataset.dataset_key'),
('ref_hs_indicator', 14, 'method', '(파생)', 'VARCHAR(300)', '산식 또는 뷰 이름'),
('ref_hs_indicator', 15, 'computed_at', '(파생)', 'DATETIME', '계산 시각'),
('ref_hs_indicator', 16, 'note', '(파생)', 'VARCHAR(300)', '해석 한계(하한선·민항 포함·1:N 중복 등)')
ON DUPLICATE KEY UPDATE column_name=VALUES(column_name), original_name=VALUES(original_name), dtype=VALUES(dtype), description=VALUES(description);

-- 검산
SELECT COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='meta_column_dict' AND COLUMN_NAME='dtype';
SELECT COUNT(*) AS n_trunc FROM meta_column_dict WHERE CHAR_LENGTH(dtype) >= 100;
SELECT COUNT(*) AS n_dict FROM meta_column_dict;
SELECT table_name, COUNT(*) AS n FROM meta_column_dict
WHERE table_name IN ('clean_dapa_localized_item', 'clean_dapa_overseas_plan', 'clean_krit_task', 'dim_hs10', 'fact_customs_monthly', 'meta_column_dict', 'meta_dataset', 'meta_load_log', 'ref_category_map', 'ref_fsc', 'ref_hs_indicator')
GROUP BY table_name ORDER BY table_name;
